def throw_exception():
    try:
        pass
    except EOFError:
        return "Exception: Something went wrong"
